extends:
  - formidable/configurations/es6-react
  - plugin:prettier/recommended

rules:
  max-len: 0
  no-magic-numbers: 0
  react/prefer-es6-class: 0
  react/no-multi-comp: 0

env:
  browser: true
  node: true
  jest: true
